{% set name = "scikit-digital-health" %}
{% set version = "0.17.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PfizerRD/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d51431b76f8af3aba76c1517a76beeec86d680b7bafa2dba8d7d3ca4975a51df

build:
  number: 0
  # script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("c") }}          # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - pip
    - numpy
    - meson
    - meson-python
    - python-build
  run:
    - python
    - numpy >=1.25.0
    - scipy >=1.12.0
    - pandas >=1.0.0
    - lightgbm >=2.3.0
    - pywavelets
    - scikit-learn
    - h5py
    - matplotlib-base
    - packaging
    - pyyaml
    - avro
    - importlib_metadata  # [py<38]

test:
  imports:
    - skdh
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PfizerRD/scikit-digital-health
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scikit Digital Health (SKDH) is a Python package with methods for ingesting and analyzing wearable inertial sensor data.
  doc_url: https://scikit-digital-health.readthedocs.io
  dev_url: https://github.com/PfizerRD/scikit-digital-health

extra:
  recipe-maintainers:
    - LukasAdamowicz
