{% set name = "scikit-digital-health" %}
{% set version = "0.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PfizerRD/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 45de73bfacf15d5dd28a7f1c9ece26834d29bc730dac8f8706e893022655c039

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<37 or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - pip
    - numpy
    - libzip
    - meson-python
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3.1
    - pandas >=1.0.0
    - lightgbm >=2.3.0
    - pywavelets
    - scikit-learn
    - h5py
    - matplotlib-base
    - packaging
    - pyyaml
    - libzip
    - importlib_metadata  # [py<38]

test:
  imports:
    - skdh
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PfizerRD/scikit-digital-health
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Scikit Digital Health (SKDH) is a Python package with methods for ingesting and analyzing wearable inertial sensor data.
  doc_url: https://scikit-digital-health.readthedocs.io
  dev_url: https://github.com/PfizerRD/scikit-digital-health

extra:
  recipe-maintainers:
    - LukasAdamowicz
